repos:
    - repo: local
      hooks:
          - id: black
            name: black
            language: system
            entry: poetry run black
            types: [python]

          - id: isort
            name: isort
            language: system
            entry: poetry run isort
            types: [python]

          - id: pyright
            name: pyright
            entry: poetry run pyright
            language: system
            types: [python]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
            args: [--maxkb=64]

          - id: mixed-line-ending
