version: "3.8"

name: weatherbot

services:
    app:
        restart: "on-failure:5"
        build:
            context: ..
            dockerfile: docker/Dockerfile
        volumes:
            - ../data:/app/data
        env_file:
            - ${ENV_PATH:-../.env}
        environment:
            - PYTHONUNBUFFERED=1
