version: "3.8"

name: weatherbot

services:
  app:
    restart: "on-failure:5"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ${ENV_PATH:-../.env}:/app/.env:ro
      - ../data:/app/data
    environment:
      - PYTHONUNBUFFERED=1 